[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "03d28dae0c19c51a0fd65a05285b984c50b84dfe"
os = "macos"

    [[GTPSA.download]]
    sha256 = "99a85270b8209626b674e8b6f91e8a3dd0b8b5f1c74781410fb3be19180adac5"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "1af4e5307af498a9d91c7dc880b923af53d6a0ed"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "5fbb24d0fe3d61b4ad9af8d488037b2ebc29201d0854ab4ba6d660a7b804f382"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "f058696f1828848e20bc1ecceb47a6eb2aca5559"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "064ed86466a8dcf818b0eae27c10ee7017fa1507ed846b35a69e4496ca07d2bc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16cca291fadbabe2f638b14920e6453fca936bff"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "fb5379eeed9f6497b413b484261611f77f2f6295fde7be8e7b67ecaaedd14972"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "367c1b0721da4bdb3d976714d8216eba4daa9807"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "a1464e50b862e55235da21d85903f2d0c597d26f257edb60b30e7dd251c4fc2e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eed9e912ed760d82a97ee5ccd802ba47910c017e"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "3cd1d39673be5fe2c4a5820b5f5b392bd1df8502b886cd6c2b93541596315795"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bbf2bafa588c0b2f46a0a63cebc2ee5a9924c4d"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "bdf8b9e958a22bc1fa2e1f013c5c3f3db8ace46cdae83176c1989410add54a27"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "4d172efdcd3a10528fc4e355db89319413e51371"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "da77a112e98e52c5bed93eb9ac918094c81968a18f7ab2423437554f27503540"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "195d1970dc648656be89ad172b49e5904bcdb9d2"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f2467475af47ca05363dafe07d2269d0f0b1ab2f48ca8b7dba5c4835ff89b890"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "7d42884765dfb609f1aba2147582eceaa29d4b57"
os = "windows"

    [[GTPSA.download]]
    sha256 = "953365da33adadb58f9fd6c56171824d3f4f2455c99b8334ef729ffebb262d8e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "03bf5b0fd08c00e5b5e4afb2bf547e0642b66e3d"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "7be19cb2704c63fd3deeeaa35e11f3e97b56e03e24843b13c6c806082e6e2fb6"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "0dea292e177c613e8fcbeb3aeb0252b190213a8b"
os = "macos"

    [[GTPSA.download]]
    sha256 = "c2203bdd9e3c3f0ca5d6e012c0a37074e2115573fee6d71e15b947e13ab8b659"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "bc784a8b10b4558dceb47ccc0997b8e6b417f631"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "9d9722f9af89824676fa00df876b4ddb7b744d001666da2c56a85b7124fdf248"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "c0b9def60a63a84d187e8a0ada6957c89f3338a0"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1116dba0bba310b5da7df19e741c6ae1a83314f6d0fc1852c1b2ec9ffe9955b5"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "2978a74f5f5f5bf62f0871d483f31fa21e82235a"
os = "windows"

    [[GTPSA.download]]
    sha256 = "7f3848b518b6fdd8a9505c28a05c19b912b65588fce845121543e47b5b6bfcba"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.3+0/GTPSA.v1.3.3.x86_64-w64-mingw32.tar.gz"
