[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "2b614b78ac21644a0d8da18867956df1f57c69f0"
os = "macos"

    [[GTPSA.download]]
    sha256 = "d5a9e968debae600c29418eadbf00a2d297eb3e02ded507297690d92ffb85a19"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "be1bc74b28ef843f4c35a5c8519ef94f6a86645d"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8f50491a4ee57c2a33c09aa5e037244aa3402b67e6d783660cb3d44c5addfb92"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "1a7b19bb4c3e3f4ecf55a579c6dd66d4b8352b7a"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "0fa6e2e225914ba9d191d9a1344b97deecafd76dcdc73e71d156f26760649e89"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9226db65da21af92ded5ca897ae733ec8898aa52"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ba78650242560987c84442de872049aa0b97fecc4cee3c637928d21b6895980c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ebd8a763cbe94e4246de068688ff6c6570606a4"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8c184c494a8b66f16aa8f752a3254c83164e8ae6d4e9accc1cc0923edd204cb2"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "890ce364ab068c7d9acf59d67fa45dcea9e86f63"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "b8a4287767d1eb8345bc9cbb53a33e610cb8a1d605845b4f35e9efa81ef6ec36"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "716d1511c41df6664439f5520f1e41794cbf2010"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "195b0d6a7f24c86393689d5b55ff77ec27ab6c9ef34d79659ed3bd3b1c59f4ac"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "0b4dabfc3ab9a990c7a7d2208e32b89fc55d4e67"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "de6fa321d7cc3a2bb6be57166c58baee8855943dd6da295c16f7a97f314e6c61"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "b0a02e56aa59585eab93ba02b9bf17511f3d9af1"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "c09ace4d6f861d2529bd2ed441542827ffdff5e321edd275dd253600884e09dc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "a792d70429e140eeadbfbfe11dc12b96557ea325"
os = "windows"

    [[GTPSA.download]]
    sha256 = "55280e2c65f975428c547fd6cd75902a2c8e66846931cb75eec4e250e2110119"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "0bf29b8732b80eec22a0edf48287dee4c3397a1c"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "05a95d0bb9d8b4e749fafdb0c1a64b6b0f1a179bc3eceebe51cb07ce07e4bc0b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "0c1deb9665696aadaeb3f6e8e9c7973f803f3672"
os = "macos"

    [[GTPSA.download]]
    sha256 = "31d1ce3e1e01966176999dcdd810e1a70af36fe1f29a4a76c7a23d8ccc38b291"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "bf89a5e6f66a64b9be0b694e159c31dc21b15574"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "cf7dca79ae433def7f6ea55c3430ebecd40bec7d300c9285466c824503f932d9"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "4702b7e5f9c4dbf849518e789eba8cf84b21a2d8"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "a374341c95a4976d2f5ed1374799221e886b366d86ca54bd4648992aa5477d9b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "858e973bc0f307fcfaf13701074554718cb494b0"
os = "windows"

    [[GTPSA.download]]
    sha256 = "2642ce8d871468f4b79cc42c3c2a8663571d9516874695182b90172f26727288"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.1+0/GTPSA.v1.3.1.x86_64-w64-mingw32.tar.gz"
