[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "8b34da0a384d55c56601a872ddab852fb7a2e62c"
os = "macos"

    [[GTPSA.download]]
    sha256 = "37acc52e7b09e32dfdab720577ac9bfdb2ad6a7862024c758cdbb1cf552228f6"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "f91eedbcba8a01c0768ac5b2198aca5b325b293d"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "5c74be83096a665927a38d28c8a2ac0427b49468895df4af1bddb7016477e76c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "67e9620e82fc08c4b0776aed00000d4704a025d3"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "93920fa36084cc2a6bccc7b1ad90fd0d471f13980c8748785b605b301830907f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "760d483954be0b198faac155544c826bc34a678c"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f4f54714c96f54ab50da98f1a44ddd54afb7842cb531434722929637f57dd297"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "393d3fac45a9fb09eb46f4303f6713ed67295475"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "bd1cd6175c7ee57bf89f6bdb427ec4fddd8cd7d13ff61cccd619714a3ec594a0"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "546d8d02096436b38d23672bd0a16eef87d02e32"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ba402cd06ebec3a25b768edefa7a7be74ac5a8a4ca267f09d706f114a6f227e4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f76d364d63a2eb3e527a0744b8e512c13fa033e2"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "618ab569840e902f89cad22c1d188798ff757b3deb3e655892efa53e23e0973d"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "6fbf4ed66ab273f55695641951e0fdd5190006c8"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "9dc563c209a8042f62d5a683c61f425887258917a3c53e28b9e0d7adea9a770c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "de489bccef485767a7e1a626cd58a197ab22b2cf"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "128791ddb632de11d61b32ea01ef05b884f14c81e5e2e60a239d7682afed7abe"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "d97c7cf42a3e2690a060da080b9aa76cba1e7695"
os = "windows"

    [[GTPSA.download]]
    sha256 = "17f6748356026f7581465bd947d085e122f66090e5abc160a313c769b20d285a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "43412275e074a0329a19f19fdad0a4112df922f9"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1c398646548c08e98e391c7eb6308a5a949c193495923ec6e16b728e2fff6c54"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "1a664b4bb849936913967ba80a9ca3b2fddb9c2c"
os = "macos"

    [[GTPSA.download]]
    sha256 = "376217c5002b0aee14ce4897f094d7f1791cfe5c349ebf605ee4fb195c196eab"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "6338cf56b7fbed6444cec1ce5c2bc1b4f4f89bbb"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "d449e7edb81829205260a560df4c0503a8c0d2750a9b58f3ec810dd9ff93480d"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "fa1296c6e476f2cdf12f2430930c33629b21884b"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "9c1247a0a6176b979fdecdccbab1f521448fcd4df1b3c3731d74acf12d1f5511"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "156648712481ea7e5b32c42e64bd28b495a11416"
os = "windows"

    [[GTPSA.download]]
    sha256 = "13a54d5f5ca66f912baf246b10c7cfe26e512fa1b20f76ac3676ee5155b83bd4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.5+0/GTPSA.v1.3.5.x86_64-w64-mingw32.tar.gz"
