[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "76ad18c2ca5862d5bf7fcb47e6e6b5f8ee8adb72"
os = "macos"

    [[GTPSA.download]]
    sha256 = "51e28126c45853f7f1bdc8d288b948c01baf5d227a184abbe6061cbed81f28b6"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "b46b787023807f6fa30140911536b640910d125f"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f0c86cfa6863849cab0480d1257cdab0b7c2bf587931a3c83c059d31900eff9a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "5300b690471cae87039f9e92d1a01bbc03870868"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2a2569e187446ff708e7300cd3732ecab39b1dea78689d01ec09528a91eb99e4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3dc1da1d2657ec7bebea0051fb308b7767bd7c4"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "496c4e7baa54723d7aeb2af3b09895ab6dd71666bbac08de365e6d82f788b35c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4abfc837be182f7940efbb89ed1d17ac9fe7d86"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ce8dd699a98207c4cf2bec3fc163b0c9b4562ae519f778a04a6409a30e5701cc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a66e2f6089c8aa47ad18907b8f3a7f6c881befa2"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "37542ec7824520440c8bb104573a23af0ff72351b7799766287c2c6d1f080862"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d27ac1c1ee253a645f99a9ec07ee2d22110c068"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "6921e64184da6b273eec4f4887117ed6be7b379a56113db2edc24c7cb08022e4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "ea13b8f9023da1cd50951edfb0cef4e529646def"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "92a8464ca5e93c3c2eab4f83b895de64a6816785bad68382170d0446ede2a355"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "6b0cd524a78890ed188b1cbc72e9ee0b1c8e0916"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2eedbe9e96a573af9368b7ec070a6ff264e4902d6d02f1a3c49990c4136d586c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "bda4f633f0b7f0bf2bd622d42e5413c75a98b398"
os = "windows"

    [[GTPSA.download]]
    sha256 = "f89235f0ce37e40935d581d95345dfb155c3ad19617bd4cf65d33bb9e028686f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "1d0a67b8465d9b449b91834ad5b475421778e090"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "0019cfdcc32a0044e24d3cbf82b2a8d7de17844eb81715fcbc62efc65a8d5b5b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "117608d87e07cb342091742b4b94aa4819a92ae4"
os = "macos"

    [[GTPSA.download]]
    sha256 = "3061724a2c829ff208d13055448bb0ddd227491dafb839fd6bc716bf978087e8"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "241407020a31b14ee01c8d72ef4555a621eab92a"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f2bc75c314d25e30b6e4efdf889a10c367566f57d55f08404002de2180d4c83f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "77db05610e58245b032de46634eb31406e912e07"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8a556db4798f672e274338cc01293ef5d0dc6127c086a6faae2c96c6c8c98030"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "b6f430be621d35f7c8d453d3132ce48179812c3e"
os = "windows"

    [[GTPSA.download]]
    sha256 = "1ddb801d9c532333c66c3783703db31d42f9657693105d1a552ce3b0b7985964"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.5.0+0/GTPSA.v1.5.0.x86_64-w64-mingw32.tar.gz"
