[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "cb7842ca67bddd788256e5b4e2600275351916e9"
os = "macos"

    [[GTPSA.download]]
    sha256 = "e57bd31401b3ad1c587c0c11bf04aca09e396108f191a23e0e0f9fa95d7eb0eb"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "4d0f15b5e6edd57469c9edc3dfedddcab38e1829"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2c5159b1035afff463aa5f0fa01c1a63f2f2f26de4f7becbc618b97e924e71a4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "20231ccab9309fbbbf62ccdfff8d37f1826eff58"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ec3f3e03411197e3cd76e3e35dfa02446e6020ad9d58f04b0b1d7562233992aa"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "472eb78325356e1e6a5f4201a36a6ce309852c01"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "e094406e955ed0da8df7f4838eba5114fc9b7dedecf4726799743a386a250034"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff21bd48b513480fdcba84a1f3c53524543db795"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "400c815bc653b75dd82bfb6ec1cbe1f744a666cbf5ff194b0ffb34ba82aaeb1a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07e92d44f96d92a480b53f257d080135842baece"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "db5bf3511ac58c5e0628edb3e9aae814e6fea2daa6020c40976c779204804d2e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ae5f3e91b883fdf36a82d691681c48e81ffbfbe"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "52900059f2d4dff4b9712254900ff6424aa31cc869f56e39fd8647ee886a063a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "592ef3fc4a5beeb3330971cf43b6164a126acfee"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1849a61e2e38b96cb3d49e835dc7ee57b9781c8745ed35913ae2a6ab9919c186"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "f287ecd1651cafe29437a3c73de3b75470727a83"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8c072aedf2b7e112edecb2b8e222f475820fd9c22c74da95a99bf4f915e7e55f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "7b5d3a6173dde335103883f34a908ee621310f07"
os = "windows"

    [[GTPSA.download]]
    sha256 = "15b3b1ab5f4e2de7859335bf86d4dedcae0b2e534f07d9e619839a9f8ed52c8b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "af17f7f8dca2ae1278376d14f8cc133cec388606"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "4388b13305eed3725f1a48e96fc449d92ad2d4827bebd4a705234aa4d9ab2c6f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "6ce574e42f8653074b05a18b0008673a057e955a"
os = "macos"

    [[GTPSA.download]]
    sha256 = "0bb6be9c79acac9aea96eb4fd16eb3e6a8265a30b14d1523930b6954a5a5cca7"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "076f7d178e595189ebaf09861562d83a36ca8a4c"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ba62c8b539ff219f40ca4b7a7b4844f8e0f14d678d25ec076b41a4af1dca07c7"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "961209d6590f90b1675e5ff3b374f775244673e7"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8fb7f2fe083f28f893d286780cd45f636c635aa2c0deb98f569f72e75a9b782f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "34ae0de51975f1bc00258d8099cc27c5c428acbc"
os = "windows"

    [[GTPSA.download]]
    sha256 = "8a2619c1721eeec8bf20b88313a1029e7d65aaed811472bf16ebfc18be48901d"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.2.0+0/GTPSA.v1.2.0.x86_64-w64-mingw32.tar.gz"
