[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "43a6fbe88fc5d0684e814f4df42e6a5af2c30c1b"
os = "macos"

    [[GTPSA.download]]
    sha256 = "916914d466e7fbd50b59aec2ccd0cde654c8ca1c1e238d48e9cb98d42cc8dd2e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "849d2a4ccc95041a4729a4262394335656783dee"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "867841a318dd60a255f5be58ed2e05b5ba93e33c0e3ff654848309c9ffa4beb7"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "c0a85c4482b17c203c78141c7c41b0da274a0673"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "7a433e157e43714ecd0ff6160b3efc3161696eccb07ff33ef43397df07203f03"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ffcb1bc9d6188793d2aaa8199b598dc8a9ad550"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "d5798ece17aa7da4d602f7e3fc907c6da85e5dc2f483888e9040e454b5ecbc84"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f877e15a2151a92c96a988e598ca5246550126d2"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ee2758a551c1e0e2c02ed0bb4f4d0c43a1c805e258ec3e2118de9389d515c491"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d9b770d8613a8f26eb963065f8805d0f21b8af8"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "3f3b0ebb6606c7f8a60b11a6faae911b0339343d7e37dcd431391df16ea254be"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cbc20b2bd4cb42367c2143726828215e364dd4e"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "7d30a18a488e4997694ef438afabf187a2c6a1c5fd6e1fbacf5ea7a783e6f83d"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "dc72463ee70059442a671b17cf61be9f5f92267e"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ffbfab2ace41fd0e9fbb5d264f8ef7e232206d0bcc098363bc694d5fe3f18258"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "5d01ac334a54fe32c2cab7b9a0846cd689c12e70"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "61aafb35cfaba578b6b3bdb4eafb60909a3d7a0ba99ee3cbda4c8e0c0c50f749"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "9aee7a41d416cca2873ea217d10235302e751d3a"
os = "windows"

    [[GTPSA.download]]
    sha256 = "5977f4d6c8c564e65c4769ef5513bbe434ec55b7ae3e3a4804309d234e8d735b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "a1cee43906e04b7f4a5d8b80a5f5949624cb43f5"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "91cfc99b8ca35d960e1617856d20295e07a7db1b3e6baa55ed93936eeb6660e4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "4bdbc076c30abd92ae33cb83917c99487d6a3a73"
os = "macos"

    [[GTPSA.download]]
    sha256 = "92c9131eb8a9fe97d49461975d05f767b8354901ee601fc95a4c73c3e328eac0"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "65cc359fff630da23fc90321dde1d8f1425450db"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "11514c78ea7b85aee040fcfa89fe00d42647567dfdc3dd424b2d24757f61776e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "97fda4c4d49ec7d69df36eadf1ef0cf862282930"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "07e3b92c3702462d011b030307a9c3b77ee440b525de13a1c55af04a13120790"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "5972b45af8e8f04b00d2f5b702dc72ce86fb7597"
os = "windows"

    [[GTPSA.download]]
    sha256 = "07e0e3915ac2890c311fe46f60bd3dde19f2cf7d3778e9a8e5812934d53c16fc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.4+0/GTPSA.v1.3.4.x86_64-w64-mingw32.tar.gz"
