[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "f0d2ff969b3e981bbd9fd1cbc991b3524ebb3039"
os = "macos"

    [[GTPSA.download]]
    sha256 = "96165edb0783e7f88fe3dfc31e6fb8c6d9a45f29eeebb3d6e837684bdb0c44a8"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "c0517fdedf304ba05f971813420c4384c052d32d"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "7f7fa890a6eeb5a429115ec97f3244c75e173ef328153f7a432b6a0131828ba1"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "043296381047968f536671934793c37415b80992"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "6a1dde9dc736a066c9402028b82a2f1a55f8392e9af35b0257346e97ee4cf505"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "28627be0c17f75905ca0d50c102f72c5e250e2ec"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "bc6e4756e2a9977f0f4dfeef94ead44d4fb970495c0ce7c6261e14505f607041"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11ab80c0f1e398cfaff03d8b40b40b676ebe124c"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "23170737a8f0437c02abd80201ae00cce7925ba676a48d1846c48f867506217f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb280f24c11d1d6b1a5d76c3e3c0e512b473e921"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8439d911ff68f113770ecf61e9cbf8924ba1c7f6703ca329db83c37764066a0f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47eb694fd916d91bcce5855ccc8094a434bf8691"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "4d2fb87cd22c94bd110c185e1afa9e3ad0a6e2810805d40a9296f4e045888bd9"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "b5b2e23a8bb36f133ad0c8e298d39542449a2384"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ce8cbe2f101a72ae106207c1cfbc4304966b4e4262dcf001215d68658e6bb59f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "54f1cd4f45faabb061ba8dc80ed7bb312846a8a7"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "e3617da9d94b68fdd268a28a3d31b091a2c543e6c22b5e7875ae079f702e8727"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "b1f14279608d9b94a3ba81554ab0a27d71a543a2"
os = "windows"

    [[GTPSA.download]]
    sha256 = "8e1595297346722aaad07f13f7ab70e0a302ce792da5b7e7ac6f25c5776feb58"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "265015b5f8cd22b23595e1affd496087d03b70da"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1a48338a3603b234eed21684988f78549279c0716708315e59d74efd40834eeb"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "riscv64"
git-tree-sha1 = "da3a981d236c0026457f1083b2c00f1998a705ba"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "174b2f5cf5960b324eec75b3c67c5e3af2d767f1c3f30ef0f54977fd7c59919b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.riscv64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "e5abd4d636da2b5e17994633ef7e1fe1a1732b33"
os = "macos"

    [[GTPSA.download]]
    sha256 = "0e4aeef73ee643dfb77ac149f358f2d389ead6b9ddd5098757aaac5d2e3b17ef"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "a3b2c9cc9ebeadf0b389fe8aea0704947a81dde4"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8e48c93de6296b163a92cb1b38ffb7a1b57950a258b0c816512d4be9ad5b9430"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "6450e17e3fbc0e55fce437efa6c17bfece7e5cbc"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1e4689afa54599d802c0d2f5ae33c5a7bdbcaf91d1e827d67fa93025a0c7cb7e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "a2ac9f96d8272451d93b6973e140ff041ffb624b"
os = "windows"

    [[GTPSA.download]]
    sha256 = "01d76808d6698f02772768a3ecd60b6376d4c78aa88f8402bc5d70803169fafa"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.6.1+0/GTPSA.v1.6.1.x86_64-w64-mingw32.tar.gz"
