[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "65c270fec290b4af54f22299772505e95fcf7392"
os = "macos"

    [[GTPSA.download]]
    sha256 = "f8deac162923e04c4b6ed7b905fc64eb8fbaea38134e9f820337daf1e87bdb9e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "598c06cf6fddce91f11352ddf54d9e9305344e68"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2b7afccce9644b30b19060ee003725a931f5121eedaefdb4dc52b5a31724b146"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "b67ca8ac38b7b382bdd52d89d8033aca92b279f6"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "784a3f9a38e10076692c91f1a7367271e603c4624687c8427ea3178aa90599ad"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75a3e2d223cfd49a3c0231fd3059fb7355301a12"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "d20ef55231a469110a8b9dd6f705d20b79cfe5a5e6ee01bc8fc5025b1704f368"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4732451bf37dae0bacc0b5382f9bda47a5d58bbc"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "3c719fa2e7c478326d78e582038bff97dfe159c8b5b21ea946efdec7ba616369"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "19108297d3e5b24bc60ab6a73c767e06a9c4e94d"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "01a10705b1cedd3fc1ff05400a1d6183bd4cfe552ed9a87bebf44b41b4269354"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8d419d0abc362189e3a579a32f2b2f47c558021"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "a8e4e83185eb99d54e4c168e8449721f4d31b0d9590eb9cb3a35d63869208a8f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "654a16aa363b027e865f50eeda9cdebe1e7b56e4"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "02c9ba4f71153ee7ff75b1d210b9ccb82a37751ca672e898a3064b921b936640"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "e0077f4c67413d11e3b7ae1c406be4ab30065aed"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "6c0c383b3485354d236831e0bb579963a4755688a0934328fcede2e570d05be3"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "87f43ab3a7e63ca3db49293d70dae1d16c29ba17"
os = "windows"

    [[GTPSA.download]]
    sha256 = "63707c5527d8a9e422336382a6a9b9f539295ca4d7e7971fd76773ae09b50480"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "ddfadd008c694c3ae0be2e6ae223ed9296f7b95f"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8db1615656a8fe7a0349c7b3fa25f472c4e888b39b6485d87e4e1f5bf2e2f397"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "fa7bdbb781bc019e9d062d2bd384e62415231e21"
os = "macos"

    [[GTPSA.download]]
    sha256 = "f313f700012eb2c3bd0b36df36eb5a81fde2c432e2a013a1fe853f9e94fc747b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "45b22975749668caffd4bfa7319e0f265ff55a81"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "6b007822ef9f34e2dfca82e10c7e1a60724e12e6512c1679b9439a1d7cea7f6c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "fe686725c78f0f767e0c8e49607d5a0f0691ccf5"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "1b056cec3f2cb49852972917979e03ab31ba74c6fbb05a0bc935b1b68c6c3a77"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "5210259e502108e5bb4d85b137edb19dbedf4017"
os = "windows"

    [[GTPSA.download]]
    sha256 = "1663b2a15b81ffdcde39b41f049999160d42a5b5fa4db6473348af9adc2e65d4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.5+0/GTPSA.v1.1.5.x86_64-w64-mingw32.tar.gz"
