[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "fecfa2c31e2d9977ada00d514b80927dc428452f"
os = "macos"

    [[GTPSA.download]]
    sha256 = "da07eaabfadd469bc0636329a8c22f0d5fd2deae64a455d3ae00136588246ead"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "7c6801cc445579f805a7a4dd8527f78587786aa2"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "532aaf4bf95d2d010e5782ad836e629da3f5ffe248e4ffb6a8fa878536e589f5"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "afd66171c1554e301f896a0b583cf7624cd096c7"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "e3e79585a0085274af1baf9935d247a95184eaa6f66ec9e56b51682059cab62e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "703a59ae481025d201f5a75e700cba40cd5a0fd3"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "821268f7c384971bbdddca70ff4bb9bfeeae32581989cecda3c2b93dd4b59c5e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3bb57fe9037c0ab8083b0ec7cdae6f1c663414c"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "341e0f9a9f726552d272de03c01bf9c3a4438f6caaec3687e6491a41b1947c5b"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "66ae671c52a215645c7ba3a8c1ebf84d2f77f7aa"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "dff1dae00d13e4c2c1e063e7caaa65f4540925e656f4e662095f43cfb5c34667"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3f66ac51b2ba53f5c3260e1cde1a5e25a4f5235"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "48d58b30013396a17d467c0cc2e2d4be082d83362c841312f0b1b692d42bbd04"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "e8e4b1743deab8b6a15fa92b7ec905c4aa3761be"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "28b9bd0088b4a39d48afe086b7c17ce353f22a1593e1471c777ed58aa96a27f2"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "7f79f3ef0f8ed213619ab13fb061e1e0e18befdd"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "745b6749034a28de0ad1027d699ff9a9b91be5f4e68a81e05ee1eceb9cf048c4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "4f117d885c167c14b54243c2f66616fdc61b16fd"
os = "windows"

    [[GTPSA.download]]
    sha256 = "bb0e72674e010d82e552e2b00fd83732dcf48eb6637508a9a6307ae66297e4a2"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "47207ef11df9887e94e9b081daf699a130654dc2"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f55a61846152af9eb94d730060f091bef6e5c7e483d2113827236137968d0027"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "997bbedcc8f14d5be1d671e27fff802d09d6ee30"
os = "macos"

    [[GTPSA.download]]
    sha256 = "57419314fd172084b2f5ad7e0be7eebd3671f5f1433596a66815aedf85c405a1"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "70bc8ed042293e5e006d9c8ea6fa867ae7481648"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f9ce9703fde820e81bedb113b81a81ddf15155feef2c91911fd44f99b4d1f363"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "02c247bf02794fa4093dab55051b018a225c57c0"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "b8a31455358fa40aaf6ad697eb1a59d3a4cb7e8822f3d34aff65524dcab3c6dc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "2474ae5fffa120792bcdb9335c05fdee4524af4c"
os = "windows"

    [[GTPSA.download]]
    sha256 = "a678f92b7c06216a27c4ce52d88bf07e01d93f614f901cc3c7c9973c300e215a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.1+0/GTPSA.v1.1.1.x86_64-w64-mingw32.tar.gz"
