[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "1653dd5ddd529de82798d5cab798922e7748d064"
os = "macos"

    [[GTPSA.download]]
    sha256 = "2f30a12771271b85005d6ef56243b40ae58f8d160a4746bac816fddd3c8f0159"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "f80436a2b6bb0e73ec99fe67e3000cca93183ecb"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "cfe60b0067121cf7a7c0ce542054b18f9c25d8561be40296482f939148146341"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "2e14127ecc8d18c0fa5176fb0d0ac5a83f3d3c3e"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "f8655639cdd1cad34c20efa068c921e47eada4df2086137af3274296b08d8ade"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9c0c4736fd96ba8c36230b3ca8afe589eb64b49"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "fdde9bc614a0fba0ce8c800693b7f26233665382f7a8d93ab0a8bfc31ce1a1fd"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "528c367ac1706069eea5c09435d4534c6a0107a2"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "64c7c18e895afafc854e6fd1acdc8fb3fc0643ce2deec82196c12288ea1a6539"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50b4cdd37c5c1252a986fd70f757e34a91de59c6"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ea954452e8be6c75adbebf684b477b167874f27c1e63a4decc4ae95269c20c5e"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d64a15e945778c65202c80e995af84d7e3095ef6"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "c232fa610d385a511ece4cc6e5a599c735d954e3764d5d726d4fa6576c0f6d95"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "f695c19d8d7fab5cb4dc83753b09024167822e66"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "e3eabd92df6a60d688f44566208919c32f7d211fb19f278fe458678be7e6f275"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "c30ea76007e083807a743e71f09bea1b402e13eb"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "b4e9b4c8fc503dbceb52eee04a481636b7f916f0ba83a1167ea5977d1ee0843c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "48db036142536f293e1c4736c3475046613984cc"
os = "windows"

    [[GTPSA.download]]
    sha256 = "48e28bdadcfc106782590000c5ea0e85211150493a321406d274b4f474ba241a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "f4a94ce47f6ac089e2b3f1b04125784e2dd53fdc"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2de7d69f017865d2d0409578eae29fd39489f0583687bce58e0bcb2616c52313"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "faf3b0fa4250626f52e7c3ba74c36bbbfa65a740"
os = "macos"

    [[GTPSA.download]]
    sha256 = "2f1465a6afd4e799e5396d78a1c628a73757cfcca4018da9b9ce89f36ff187e0"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "48e4605dd1cb7e550d4cfb35642c02fd2cd4b7ec"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "30d045958c35df3bfe0121bcba7bd956fa20db6b141857a27ccfb9dd201d31fb"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "6febf4aae25acb1c135ad5057394d417707b6122"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "36140c05da37ffb636816c809dc882cc15daf5d75c67623bc544326adcebf4e8"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "6ea86edef832a308fa59e08ffb0f7d6f9b70658e"
os = "windows"

    [[GTPSA.download]]
    sha256 = "4e360727563db7de1d80c59008dbe0994034bec675b668a8d05a67e6b76ec1d1"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.4+0/GTPSA.v1.1.4.x86_64-w64-mingw32.tar.gz"
