[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "9b3a0d7eb86f6ea55865b2493fbf9667e1389d4e"
os = "macos"

    [[GTPSA.download]]
    sha256 = "3672bf0d6fe3e1471de62af4f33b41785c2ae0346eaba75692ee77de87af7023"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "90e9808a16aff1858b6dd7a96ef0bad30b867bca"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "2cd509b81d6996f65f213407e1b8dcbd52c85e604178224002517dfb3ff67366"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "6a8add0126618ccb1f854610bf591626b999dc6d"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "803f5cb0d1bbb7151703af6354ce5c743901b5fa44c9897a271a8bf372e65f32"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "811d066073f806a33c23c77f7bbfe71140dbdbe1"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "6f447b38707ec40d544b901e28d270d644199c6c27c52c10b797fcac92cbdd73"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3171738dd5aafae2f5f2aa77d3a773113366e06"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "31b536f1d871d97e37947a65d6f2ec7b3ad30ebab63eb0252741ab7578558d77"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36a58a902aa8a38216603ca96961c6f1c19d8402"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "4675e47002fb6609f546448e3f4c3cb3e85abfab5b49e6ac33d05842f5186783"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b27172245762ef204cd8317df843f4e582d2563"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "012e7039dc8b0435ad92f0392bbbc7564cb0f2d391f0ca487c737d53465174c5"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "9d6672e27bb3da0d60ae06f3361ebc8f9584a5d0"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "d8d1ab14adba917bb446031cde0c54f5b6407511116b24799b2e20772ab0a904"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "d64efa3d77604cd87397cc289c567f03efb304a2"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "301cef7311278034789aa6d273c32bb15aa2b38f98d1c0eb397cc8e4fda32f21"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "cb56ca5d4eca0213365092d935c67adb82befba9"
os = "windows"

    [[GTPSA.download]]
    sha256 = "3822d80bbaea342239f4086b7782105d6cb9637bab7d58dc44f9681e15c496b5"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "6d8c7c94525bf328874c127e15d1cb41b2ed88c8"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "30feaa3bde80b03f5a34475c2bce141458c634f97b6be499f843635b67606dd1"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "496fea61cf5f7ec4a0125cac8f55476617b13347"
os = "macos"

    [[GTPSA.download]]
    sha256 = "61345cb452e0759684696904a08bc735c06d55cd0ed72d39324f9735233abd10"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "cfe7f52539717985f3b11a4a8273c895716acabc"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8be5513baa84acbc5b682f53049e46a957c789c2888026d4422afc4c9376dc1a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "16100b36b6b1de865b67305fe3f4972d37e879df"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "caa1ed8f3c5e7ed14f4c8a00797458bedbcf4d353fd6dc8f6f868c6127d29443"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "1f408f8d719bc1b6396a22eb8b2ffcf96db5ada5"
os = "windows"

    [[GTPSA.download]]
    sha256 = "e9136d385f9f0c14a87f4bdfcb7fc4d4719c954d2498043a176a804406749aa4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.0+0/GTPSA.v1.3.0.x86_64-w64-mingw32.tar.gz"
