[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "c375e8488f7cd89d79fd7642afa36a5befcd3c3c"
os = "macos"

    [[GTPSA.download]]
    sha256 = "800935065dffd78c10034b71ea4780f210fd08398154c2fa3e0e2eb733cd3d54"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "8ee859cac1a2cb1a31896a9a19c003bef2973717"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "b68eaddbbe37506e6bb5c10de16e6f765a352451ad3d5c954611d697bc12d623"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "0d8d181c5bddb8b89a41576a4f5a6dba76f073b7"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "a25da233fa4255a4c98f0c245feb06daa40e54a3620c1514a7bc2f85de6dd545"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4cd59070995335d3a19a08ba25f710f44d3f075f"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "fe3db6bd36adf4d2ac5c966c69084595aba03a92e7b203b8a0dec9667bdd6347"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6be199fc51a688ac816a6eb3eb16a8d98304c40"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "7e5986caec9757a38c0cf2a3b730bf4e1abae8d9b6199e0736b6b511fb413ffb"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc1ff1df8b6880895ba77ea387c8fa6eb761c00b"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "0d3ee7e8a419b53c384204b90cbc986053712e6d3b738cb23d99bf6a95877747"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d26cf59c2c7dfced041a28e3e06f8d82c3c12fb"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "25ebead200ebc1621df26130a55888bccc84f572936da4317b8f49babe4ed62f"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "839559c6ac41908e55a3c9ed251d10830d65bf55"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "66d636602c324f6669b19db1901871bfde8cdc8aa97bef862a4e1156b86af220"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "63d20a73de1318781031889454982bc3df2b9e12"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "b504137641424c8c0bb3a88d7749bed58288108e7e2b0a8c51ef6ec694df34e0"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "a06b679daf0cae1f975775ab4855a5b062c78d76"
os = "windows"

    [[GTPSA.download]]
    sha256 = "86371cd4697985e5a1185e34a01d4cc13cd966e562570f6a6c0d4b17e9b93f3c"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "5f28d035d617ab9618d7e3c37c7e8b01bf1f1ee1"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "643a14deb01558ecbbee4de8e664d6c037b4f65f2a1d96ff4e7c0fb37cb4391a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "7026a71f75239eabb35cc26a769dfd7b745e6fc5"
os = "macos"

    [[GTPSA.download]]
    sha256 = "f40ef3ce6068401db74db6c5f24d7ca6cbadaf47fa8901984abe8a2d37948588"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "022d8d1748ebca26a2834e9a85daeb00293fbcb5"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "0a7b6862481c7fe28f7d626c86cb5569dd6ce75ce77c28abedd93767d71b05d3"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "84d1e7e85792dddf9a3b5e00c428bcda4641b273"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "c4842ea9723effb8ab1e46e8a97248a0667061a44ea30a4b689930ef16d45532"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "fd39620215fb9c2d2a2420347fdb38361a7ef972"
os = "windows"

    [[GTPSA.download]]
    sha256 = "a61ec3920bcfb6346c26fba5fbe9f1207d9c98903194fabc4ea2c3c1b5f9d6c8"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.3.2+0/GTPSA.v1.3.2.x86_64-w64-mingw32.tar.gz"
