[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "d31eb390099df59cfb0a3b36b86778f95f385d50"
os = "macos"

    [[GTPSA.download]]
    sha256 = "a0b5cccd7c7b0f7a48b330390a3cb95b10ce4d3a9c375c0445daa475ad63bb27"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.aarch64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "67cad6ad4234c09e84e864b955defc6ed10fe7aa"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "41532213726cdaa4123216260a031264be191327c62c7f065ae2347db03bcb00"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.aarch64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "aarch64"
git-tree-sha1 = "7df5e47ad304ef2e55e57aaf525436e4a5aa7d52"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "bc04d9499093915d8aac43371e7723cdf654162974f49c0b6e2845df6add13d4"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.aarch64-linux-musl.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "96c4d1a74ca775c4a72d7aba1d4a1c8173bbc3ab"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "a153f1276e4d28786a3dfe6e9da1ea2c39da8ad6bc4ca6ae8e8c2260cf922b69"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.armv6l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ab4d21071824fe954de9e53cc4e83a444c8ee44"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "014ea151c050529978abd59f7d97ef6dcde5f772252e417bbe9c02432dd3ba88"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.armv6l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5fac44890fbddde15a48c0b7b7840406f27dcbd3"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8a5d7e1aa6bafb3cc096ad7e6fc589435d72cef275ca87617a8e01b69077da52"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.armv7l-linux-gnueabihf.tar.gz"
[[GTPSA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c6d833fddc8ce518c4d0f66927e032b0f4167ce"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "ea847a2729529d23e6f16a2a4b3011c03bad2a5cbd13b1b4b2cb6b22b5038bec"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.armv7l-linux-musleabihf.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "a26c541f0069f6deb9f9a337ee24e97e68e6021e"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "281cd1290142935c6308b5339ba68021e31181e538a81df55a6ccd9a76b30abc"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.i686-linux-gnu.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "579937cd1abe0ada67e5b7d32e5fd461fe67ad1a"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "17c606883efbd0922fd88172cbf2990c395ab8c9cc8075ffd7d15f3144946798"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.i686-linux-musl.tar.gz"
[[GTPSA]]
arch = "i686"
git-tree-sha1 = "3d3e921d440310cc696a3865b5cbffd19dd1da54"
os = "windows"

    [[GTPSA.download]]
    sha256 = "e72b538ea330bd245f0c4d820719940a5ef8cfdba5c40779c15a2a2a22080309"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.i686-w64-mingw32.tar.gz"
[[GTPSA]]
arch = "powerpc64le"
git-tree-sha1 = "405bdabd99d5934b102997fd6813fba4f3e3d1ff"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "8822e80a472be7e324433f1b18d075b245bb02848189a31586bed5102666c83a"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.powerpc64le-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "c2540244a15ae4f6b47c09f0458cec1aaa805a2f"
os = "macos"

    [[GTPSA.download]]
    sha256 = "8ed0ea2672c9274a6dca4950094e34ce66ff915db1996c279b1c604718526fc7"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.x86_64-apple-darwin.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "45c8342773c95a2c16a56ed49ff9c45e31a425fa"
libc = "glibc"
os = "linux"

    [[GTPSA.download]]
    sha256 = "68357a7af0e6fca763aa20ef574717b511177062f3143729eb42edfad94a6ef7"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.x86_64-linux-gnu.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "b5882de0050ae86f6f684d9602c0fafbaedfd6d1"
libc = "musl"
os = "linux"

    [[GTPSA.download]]
    sha256 = "20427a12002980232379dec856ea675b436f1e3b7643b8afbe347c7d8072c766"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.x86_64-linux-musl.tar.gz"
[[GTPSA]]
arch = "x86_64"
git-tree-sha1 = "a8c64028bf4a03606a325d03d04bb120ad90e87b"
os = "windows"

    [[GTPSA.download]]
    sha256 = "a12ea79d501644bec20aa3ba32475359c575a23bfda266b20df6bd0b172ea964"
    url = "https://github.com/JuliaBinaryWrappers/GTPSA_jll.jl/releases/download/GTPSA-v1.1.3+0/GTPSA.v1.1.3.x86_64-w64-mingw32.tar.gz"
